# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      # Runs a single command using the runners shell
#       - name: Check Environment and Update Status
#         run: |
#           pwd
#           cd $GITHUB_WORKSPACE
#           ls
#           echo 3 > status.txt
#           cat status.txt

      # Runs a set of commands using the runners shell
      - name: Update Status and Push to Repo
        run: |
          git remote set-url origin git@github.com:TravisLazar/StatusCode.git
          git config --global user.name "Status Bot"
          git config --global user.email "Status Bot"
          
          ls
          cat status.txt
          echo 3 > status.txt
          cat status.txt
          
          git status
          git add --all
          git commit -m "Updating status to AVAILABLE"
          git fetch origin main
          git push origin HEAD:main
        
          

        
#       - uses: actions/checkout@v1
#       - name: Run a one-line script
#         run: python ./.github/workflows/todo_List.py
#       - name: switching from HTTPS to SSH
#         run: git remote set-url origin ${{ secrets.ssh }}
#       - name: check for changes
#         run: git status
#       - name: stage changed files
#         run: git add .
#       - name: commit changed files
#         run: git commit -m "Auto updating TODO.txt"
#       - name: fetch from master
#         run: git fetch origin master
#       - name: push code to master
#         run: git push origin HEAD:master
